"use client";
import { useState, useCallback } from "react";
import { motion } from "framer-motion";
import { FileText, CheckCircle2, XCircle, RotateCcw, ChevronLeft, Trophy, Volume2 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useVocab } from "@/lib/vocab-context";
import { useAuth } from "@/hooks/use-auth";
interface LP{a:string;aP:string;b:string;bP:string;c:"a"|"b";}
interface IC{e:string;iu?:string;o:{h:string;p:string}[];c:number;}
interface MP{q:string;qp:string;qv:string;a:{h:string;p:string;v:string}[];c:number;}
interface FB{wb:{h:string;p:string}[];s:{h:string;p:string;a:string;v:string}[];}
type ED={l:LP[];ic:IC[];m:MP[];fb:FB;};
type P="intro"|"playing"|"result";
function sh<T>(a:T[]):T[]{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
const w=typeof window!=="undefined"?window:undefined;
function sp(t:string){if(!w||!("speechSynthesis"in w))return;const u=new SpeechSynthesisUtterance(t);u.lang="zh-CN";u.rate=0.9;const v=w.speechSynthesis.getVoices();const z=v.find((x:any)=>x.lang.startsWith("zh"));if(z)u.voice=z;w.speechSynthesis.cancel();w.speechSynthesis.speak(u);}
function genL(v:any[]):LP[]{const p=sh(v).slice(0,20);const r:LP[]=[];for(let i=0;i<10&&i+1<p.length;i+=2){r.push({a:p[i].han,aP:p[i].pinyin,b:p[i+1].han,bP:p[i+1].pinyin,c:Math.random()>0.5?"a":"b"});}return r;}
function genI(v:any[]):IC[]{const wi=v.filter((x:any)=>x.imageUrl&&x.imageUrl.length>0);const we=v.filter((x:any)=>x.emoji&&x.emoji.length>0&&!x.imageUrl);const p=sh([...wi,...we]).slice(0,10);return p.map((w:any)=>{const d=sh(v.filter((x:any)=>x.id!==w.id&&x.han!==w.han)).slice(0,3);const o=sh([w,...d]).map((x:any)=>({h:x.han,p:x.pinyin}));return{e:w.emoji,iu:w.imageUrl,o,c:o.findIndex((x:{h:string})=>x.han===w.han)};});}
function genM(v:any[]):MP[]{const p=sh(v).slice(0,10);return p.map((w:any)=>{const d=sh(v.filter((x:any)=>x.id!==w.id)).slice(0,3);const a=sh([w,...d]).map((x:any)=>({h:x.meaning,p:x.pinyin,v:x.exampleVi||x.meaning}));return{q:w.example||w.han+"。",qp:w.examplePinyin||w.pinyin+"。",qv:w.exampleVi||w.meaning,a,c:a.findIndex((x:{h:string})=>x.han===w.meaning)};});}
function genF(v:any[]):FB{const p=sh(v).slice(0,10);const wb=sh(p).map((w:any)=>({h:w.han,p:w.pinyin}));const s=p.map((w:any)=>{const ex=w.example||w.han+"。";const exp=w.examplePinyin||w.pinyin+"。";const exv=w.exampleVi||w.meaning+"。";return{h:ex.replace(w.han,"（  ）"),p:exp,a:w.han,v:exv};});return{wb,s};}
function genE(v:any[],s:number):ED{const s2=[...v];let s3=s;for(let i=s2.length-1;i>0;i--){s3=(s3*9301+49297)%233280;const j=Math.floor((s3/233280)*(i+1));[s2[i],s2[j]]=[s2[j],s2[i]];}return{l:genL(s2),ic:genI(s2),m:genM(s2),fb:genF(s2)};}
export function ExamPage(){
const VOCAB=useVocab();const{user,submitScore}=useAuth();const[Pf,setPf]=useState<P>("intro");const[ei,setEi]=useState(0);const[e,setE]=useState<ED|null>(null);const[a,setA]=useState<Record<string,any>>({});const[sc,setSc]=useState(0);const[tq,setTq]=useState(0);
const st=useCallback((i:number)=>{setE(genE(VOCAB,(i+1)*12345));setEi(i);setA({});setSc(0);setPf("playing");},[VOCAB]);
const sb=useCallback(()=>{if(!e)return;let c=0,t=0;e.l.forEach((p,i)=>{t++;if(a[`l${i}`]===p.c)c++;});e.ic.forEach((q,i)=>{t++;if(a[`i${i}`]===q.c)c++;});e.m.forEach((q,i)=>{t++;if(a[`m${i}`]===q.c)c++;});e.fb.s.forEach((s,i)=>{t++;if(a[`f${i}`]===s.a)c++;});setSc(c);setTq(t);setPf("result");if(user&&submitScore)submitScore("flashcard_review",c*10,{exam:true,correct:c,total:t}).catch(()=>{});},[e,a,user,submitScore]);
if(Pf==="intro")return(<div className="flex flex-col gap-4"><Card className="p-6 md:p-8 border-0 bg-gradient-to-br from-rose-100 via-fuchsia-50 to-violet-100"><div className="flex items-center gap-3 mb-4"><div className="w-12 h-12 rounded-xl bg-gradient-to-br from-rose-500 to-violet-500 flex items-center justify-center shadow-md"><FileText className="h-6 w-6 text-white"/></div><div><h2 className="text-2xl font-bold">Đề thi kết thúc khóa</h2><p className="text-sm text-muted-foreground">10 đề thi ngẫu nhiên • 40 câu/đề</p></div></div><div className="p-3 rounded-xl bg-white/70 border border-rose-200"><div className="font-semibold text-sm mb-1">📋 Cấu trúc (10đ)</div><ul className="text-xs text-muted-foreground space-y-1"><li>I. Phần nghe (2đ • 10 câu)</li><li>II. Chọn Hán tự theo hình (2đ • 10 câu)</li><li>III. Nối câu ví dụ (3đ • 10 câu)</li><li>IV. Điền chỗ trống (3đ • 10 câu)</li></ul></div></Card><div className="grid grid-cols-2 md:grid-cols-5 gap-3">{Array.from({length:10}).map((_,i)=>(<motion.button key={i} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*0.05}} onClick={()=>st(i)} className="p-4 rounded-2xl bg-gradient-to-br from-violet-500 to-fuchsia-500 text-white hover:scale-105 transition-transform shadow-md"><div className="text-3xl mb-1">📝</div><div className="font-bold">Đề {i+1}</div><div className="text-xs opacity-80">40 câu • 10đ</div></motion.button>))}</div></div>);
if(Pf==="result"&&e){const pct=Math.round((sc/tq)*100);const pts=sc*10;const em=pct>=80?"🏆":pct>=60?"🎉":pct>=40?"💪":"📚";const ti=pct>=80?"Xuất sắc!":pct>=60?"Tốt lắm!":pct>=40?"Cố lên!":"Cần luyện thêm!";return(<Card className="p-8 flex flex-col items-center gap-6 text-center bg-gradient-to-br from-emerald-50 via-teal-50 to-cyan-50 border-0"><div className="text-7xl">{em}</div><div><h3 className="text-3xl font-bold mb-1">{ti}</h3><p className="text-muted-foreground">Đề {ei+1}</p></div><div className="text-6xl font-bold bg-gradient-to-r from-emerald-500 to-teal-500 bg-clip-text text-transparent">{sc}/{tq}</div><Badge variant="secondary" className="text-base px-4 py-1">{pct}% • {Math.round((sc/tq)*10)}/10đ</Badge><div className="w-full p-4 rounded-2xl bg-white/70 border border-emerald-200"><div className="text-xs uppercase tracking-wider text-muted-foreground mb-1">Điểm chăm chỉ</div><div className="text-4xl font-bold bg-gradient-to-r from-emerald-500 to-teal-500 bg-clip-text text-transparent">+{pts}</div><div className="text-xs text-muted-foreground mt-1">{sc}×10 {user?"• Đã lưu 🎉":"• Đăng nhập để lưu"}</div></div><div className="flex gap-3"><Button onClick={()=>st(ei)} className="gap-2 bg-gradient-to-r from-emerald-500 to-teal-500 text-white"><RotateCcw className="h-4 w-4"/>Làm lại</Button><Button variant="outline" onClick={()=>setPf("intro")} className="gap-2"><ChevronLeft className="h-4 w-4"/>Chọn đề khác</Button></div></Card>);}
if(!e)return null;return(<div className="flex flex-col gap-5"><div className="flex items-center justify-between gap-4"><button onClick={()=>setPf("intro")} className="text-sm text-muted-foreground hover:text-foreground flex items-center gap-1"><ChevronLeft className="h-4 w-4"/>Thoát</button><Badge variant="secondary">📝 Đề {ei+1}</Badge><Button onClick={sb} className="gap-2 bg-gradient-to-r from-rose-500 to-violet-500 text-white"><Trophy className="h-4 w-4"/>Nộp bài</Button></div>
<Card className="p-5 border-2 border-rose-200"><h3 className="font-bold text-lg mb-1">I. Phần nghe (2đ)</h3><p className="text-sm text-muted-foreground mb-4">🔊 Bấm nghe, chọn A hoặc B</p><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{e.l.map((p,i)=>(<div key={i} className="flex items-center gap-2 p-3 rounded-xl bg-rose-50/50"><span className="font-mono text-sm font-bold w-6">{i+1}.</span><button onClick={()=>sp(p.c==="a"?p.a:p.b)} className="w-10 h-10 rounded-full bg-rose-500 text-white flex items-center justify-center shrink-0 hover:bg-rose-600"><Volume2 className="h-4 w-4"/></button><div className="flex gap-1"><button onClick={()=>setA(a=>({...a,[`l${i}`]:"a"}))} className={`px-3 py-1.5 rounded-lg text-sm ${a[`l${i}`]==="a"?"bg-rose-500 text-white":"bg-white border border-rose-200 hover:bg-rose-100"}`}>A. {p.a}</button><button onClick={()=>setA(a=>({...a,[`l${i}`]:"b"}))} className={`px-3 py-1.5 rounded-lg text-sm ${a[`l${i}`]==="b"?"bg-rose-500 text-white":"bg-white border border-rose-200 hover:bg-rose-100"}`}>B. {p.b}</button></div></div>))}</div></Card>
<Card className="p-5 border-2 border-amber-200"><h3 className="font-bold text-lg mb-1">II. Chọn Hán tự theo hình (2đ)</h3><p className="text-sm text-muted-foreground mb-4">Chọn Hán tự đúng với hình</p><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{e.ic.map((q,i)=>(<div key={i} className="p-3 rounded-xl bg-amber-50/50"><div className="flex items-center gap-2 mb-2"><span className="font-mono text-sm font-bold w-6">{i+1}.</span>{q.iu?(<img src={q.iu} alt="" className="w-20 h-20 object-cover rounded-lg shadow-sm" onError={(e:any)=>{e.target.style.display='none';}}/>):(<span className="text-4xl">{q.e}</span>)}</div><div className="grid grid-cols-2 gap-2">{q.o.map((o,j)=>(<button key={j} onClick={()=>setA(a=>({...a,[`i${i}`]:j}))} className={`px-3 py-2 rounded-lg text-sm font-bold ${a[`i${i}`]===j?"bg-amber-500 text-white":"bg-white border border-amber-200 hover:bg-amber-100"}`}>{o.h}<span className="text-xs italic font-normal opacity-70 ml-1">{o.p}</span></button>))}</div></div>))}</div></Card>
<Card className="p-5 border-2 border-teal-200"><h3 className="font-bold text-lg mb-1">III. Nối câu ví dụ ↔ đáp án (3đ)</h3><p className="text-sm text-muted-foreground mb-4">Đọc câu, chọn đáp án</p><div className="space-y-2">{e.m.map((q,i)=>(<div key={i} className="p-2 rounded-lg bg-teal-50/50"><div className="flex items-center gap-2 mb-1"><span className="font-mono text-sm font-bold w-6">{i+1}.</span><button onClick={()=>sp(q.q)} className="text-teal-500">🔊</button><span className="text-sm font-medium truncate">{q.q}</span></div><div className="text-xs italic text-muted-foreground ml-8">{q.qp}</div><select value={a[`m${i}`]!==undefined?String(a[`m${i}`]):""} onChange={(e:any)=>setA(a=>({...a,[`m${i}`]:parseInt(e.target.value)}))} className="mt-1 ml-8 px-2 py-1 rounded-lg border border-teal-200 text-sm bg-white"><option value="">Chọn...</option>{q.a.map((an,j)=>(<option key={j} value={j}>{an.h}</option>))}</select></div>))}</div></Card>
<Card className="p-5 border-2 border-violet-200"><h3 className="font-bold text-lg mb-1">IV. Điền chỗ trống (3đ)</h3><p className="text-sm text-muted-foreground mb-3">Chọn từ điền vào ( )</p><div className="flex flex-wrap gap-2 mb-4 p-3 rounded-xl bg-violet-50">{e.fb.wb.map((wd,i)=>(<span key={i} className="px-2 py-1 rounded-lg bg-white border border-violet-200 text-sm font-medium">{wd.h}<span className="text-xs italic text-muted-foreground ml-1">{wd.p}</span></span>))}</div><div className="space-y-2">{e.fb.s.map((s,i)=>(<div key={i} className="flex items-center gap-2 p-2 rounded-lg bg-violet-50/50"><span className="font-mono text-sm font-bold w-6">{i+1}.</span><div className="flex-1"><div className="text-sm">{s.h}</div><div className="text-xs italic text-muted-foreground">{s.p}</div></div><select value={a[`f${i}`]||""} onChange={(e:any)=>setA(a=>({...a,[`f${i}`]:e.target.value}))} className="px-2 py-1 rounded-lg border border-violet-200 text-sm bg-white min-w-[80px]"><option value="">（ ）</option>{e.fb.wb.map((wd,j)=>(<option key={j} value={wd.h}>{wd.h}</option>))}</select></div>))}</div></Card>
<div className="sticky bottom-4 flex justify-center"><Button onClick={sb} size="lg" className="gap-2 bg-gradient-to-r from-rose-500 to-violet-500 text-white shadow-lg"><Trophy className="h-5 w-5"/>Nộp bài thi</Button></div></div>);}
